Output demo.gif

Set WindowBar Colorful

Set FontSize 32

Set Width 1980
Set Height 1400

Set FontFamily "FiraCode Nerd Font"


Set Theme "Catppuccin Mocha"

Set Margin 24
Set MarginFill "#674EFF"
Set BorderRadius 12

Type "accli"

Sleep 1s

Enter

Sleep 1s

Type "Hunter X Hunter"

Enter

Sleep 1s

Up

Sleep 1s

Enter

Sleep 3s

Space 
Sleep 1s
Down
Space
Sleep 1s
Down
Space

Sleep 1s

Enter 
Enter

Enter

Sleep 3s
